version: "3"  
services:
     grafana:
          image: grafana/grafana:7.5.7
          ports:
               - "3000:3000"
          volumes:
               - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
               - grafana-data:/var/lib/grafana

      
volumes:
  grafana-data:


