version: "3"
services:
  app: 
    build:
      context: app 
    ports:
      - "5000"
  nginx:
    image: nginx:latest 
    volumes: 
      - /home/delameta/My-DevOps-Journey/nginx/deploy_flask_with_nginx/app/nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - app 
    ports:
      - "80:80"
       