version: "3"  
services:
     prometheus:
          image: prom/prometheus:latest
          ports: 
          - 9090:9090
          volumes:
          - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
     app:
          container_name: app
          build: ./app/.
          ports:
          - "5000:5000"
          volumes:
          - "./app/app.py:/app.py"

