global:
	scrape_interval: 5s 
	external_labels: 
		monitor: 'node'
scrape_configs:
	- job_name: 'prometheus' 
	  static_configs: 
	  	- targets: ["localhost:9090"]
	- job_name: 'node'
	  static_configs:
	  	- targets: ["localhost:9100"]
	  	
